permalink: pretty

collections:
  projects:
    output: true
  journal:
    output: true

baseurl: ""
relativeurls: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: "/journal/*"
    values:
      layout: "red_block"
  - scope:
      path: ""
      type: "journal"
    values:
      layout: "journal"
  - scope:
      path: ""
    values:
      layout: "default"